app:
  scheduler:
    enable: true
    interval: 7s
    force-check-delay: 10s
  github-base-url: https://api.github.com
  stack-overflow-base-url: https://api.stackexchange.com/2.3
  bot-base-url: https://localhost:8090
  connection-type: jdbc

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:scrapper
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml


