app:
  telegram-token: unset
  client-retry:
    retry-policy: linear
    delay: 2
    max-attempts: 3
    supported-errors: [404, 403, 400]

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
