/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.TgchatRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.14"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tgchat extends TableImpl<TgchatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TGCHAT</code>
     */
    public static final Tgchat TGCHAT = new Tgchat();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TgchatRecord> getRecordType() {
        return TgchatRecord.class;
    }

    /**
     * The column <code>TGCHAT.ID</code>.
     */
    public final TableField<TgchatRecord, Long> ID =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Tgchat(Name alias, Table<TgchatRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tgchat(Name alias, Table<TgchatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TGCHAT</code> table reference
     */
    public Tgchat(String alias) {
        this(DSL.name(alias), TGCHAT);
    }

    /**
     * Create an aliased <code>TGCHAT</code> table reference
     */
    public Tgchat(Name alias) {
        this(alias, TGCHAT);
    }

    /**
     * Create a <code>TGCHAT</code> table reference
     */
    public Tgchat() {
        this(DSL.name("TGCHAT"), null);
    }

    public <O extends Record> Tgchat(Table<O> child, ForeignKey<O, TgchatRecord> key) {
        super(child, key, TGCHAT);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<UniqueKey<TgchatRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_9);
    }

    @Override
    @NotNull
    public Tgchat as(String alias) {
        return new Tgchat(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Tgchat as(Name alias) {
        return new Tgchat(alias, this);
    }

    @Override
    @NotNull
    public Tgchat as(Table<?> alias) {
        return new Tgchat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Tgchat rename(String name) {
        return new Tgchat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Tgchat rename(Name name) {
        return new Tgchat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Tgchat rename(Table<?> name) {
        return new Tgchat(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
