/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.Task;
import edu.java.domain.jooq.tables.Tgchat;
import edu.java.domain.jooq.tables.records.LinkRecord;
import edu.java.domain.jooq.tables.records.TaskRecord;
import edu.java.domain.jooq.tables.records.TgchatRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.14"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<TaskRecord> CONSTRAINT_272D = Internal.createUniqueKey(Task.TASK,
        DSL.name("CONSTRAINT_272D"),
        new TableField[] {Task.TASK.CHAT_ID, Task.TASK.LINK_ID},
        true
    );
    public static final UniqueKey<TgchatRecord> CONSTRAINT_9 =
        Internal.createUniqueKey(Tgchat.TGCHAT, DSL.name("CONSTRAINT_9"), new TableField[] {Tgchat.TGCHAT.ID}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TaskRecord, TgchatRecord> CONSTRAINT_27 = Internal.createForeignKey(Task.TASK,
        DSL.name("CONSTRAINT_27"),
        new TableField[] {Task.TASK.CHAT_ID},
        Keys.CONSTRAINT_9,
        new TableField[] {Tgchat.TGCHAT.ID},
        true
    );
    public static final ForeignKey<TaskRecord, LinkRecord> CONSTRAINT_272 = Internal.createForeignKey(Task.TASK,
        DSL.name("CONSTRAINT_272"),
        new TableField[] {Task.TASK.LINK_ID},
        Keys.CONSTRAINT_23,
        new TableField[] {Link.LINK.ID},
        true
    );
}
